### ISSUE TITLE
'Cannot register any Logger instances after the first call of getLogger() method'

### ISSUE THREAD

**Issue by sjl2024** [szjani/lf4php#4]
What is the purpose of blocking the behavior described in the above message? I'm using async code and this exception is causing problems in the way that I init my resources. Is there some way I can modify your facade so that I can define loggers whenever I want in my code?

Edit: this behavior occurs using the lf4php/monolog impl

**Comment by szjani** [comment]
This is a feature in lf4php, independent from the implementation. The idea behind it is that if you can register in loggers after you have already used one may have side effect and could have unpredictable outcome. A logger registration affects not just the logger for that particular name, but the whole path to the leaf in the tree.

```php
$factory->registerLogger('foo', $logger1);
$factory->registerLogger('foo/bar', $logger2);
$factory->getLogger('foo/bar/baz'); // returns $logger2
//----------------
$factory->registerLogger('foo', $logger1);
$factory->getLogger('foo/bar/baz'); // returns $logger1
$factory->registerLogger('foo/bar', $logger2);
$factory->getLogger('foo/bar/baz'); // return what?
```

As you can see in the above example, the getLogger() returns different loggers. In the second case, $logger1 is binded to foo/bar/baz, however foo/bar is more specified, $logger2 should be returned. But calling getLogger() with the same name should return the same logger all the time.
